# Block 1

In [44]:
# import libraries
import pandas as pd
from google.colab import files

# Block 2

In [45]:
# load data
files.upload()
data = pd.read_csv('problem_set_1_data.csv')

# rename columns
data = data.rename(columns={'quizzes': 'quiz_total', 'attendedClass': 'attended', 'finalgrade': 'final_grade', 'final_EXAM': 'final_exam', 'student': 'name'})

# print head, tail, and summary of df
print('------------ 2a ------------')
print(data.head())
print('------------ 2b ------------')
print(data.tail())
print('------------ 2c ------------')
print(data.describe())

Saving problem_set_1_data.csv to problem_set_1_data (1).csv
------------ 2a ------------
   quiz_total  attended  final_grade  final_exam               name
0       78.50         1        99.38          46       Linnie Lietz
1       64.25         0        95.78          45      Mitch Mustain
2       76.75         0        97.42          41     Salina Chavera
3       69.00         1        92.50          38  Kimberely Conwell
4       64.00         0        92.50          39          Zack Burk
------------ 2b ------------
     quiz_total  attended  final_grade  final_exam                 name
166        73.5         0        96.25          45           Dana Malta
167        75.5         0        98.13          44         Sixta Heyden
168        41.0         0        69.38          32       Brianne Broome
169        77.0         0       101.25          47  Elouise Weatherholt
170        72.0         0        92.81          38        Addie Maharaj
------------ 2c ------------
       quiz_total    attended  final_grade  final_exam
count  171.000000  171.000000   171.000000  171.000000
mean    69.131579    0.192982    91.855380   39.672515
std      9.488473    0.395798     9.487795    5.511304
min      0.000000    0.000000     2.500000    0.000000
25%     65.500000    0.000000    89.380000   37.000000
50%     72.000000    0.000000    93.130000   40.000000
75%     75.500000    0.000000    96.360000   44.000000
max     79.500000    1.000000   104.380000   49.000000

Describe what the averages from the dataframe mean:
* The averages refer to the average quizzes grades, final grades, and final exam grades of the class overall. The average quiz grade was a 69.13, the average final grade was a 91.85, and the average final exam score was a 39.67.

# Block 3

In [4]:
# subset data by whether someone attended class
#new_dfs = data.groupby(data.attended) 
#attended_df = new_dfs.get_group(1)
#did_not_attend_df = new_dfs.get_group(0)

boolean1 = data['attended'] == 1
boolean0 = data['attended'] == 0

print('------------ 3a ------------')
print(data[boolean1])
print('------------ 3b ------------')
print(data[boolean0])

# find average of quiz_total, final_grade, and final_exam for both subsets
print('------------ 3c ------------')
print(data[boolean1].describe())
print('------------ 3d ------------')
print(data[boolean0].describe())

------------ 3a ------------
     quiz_total  attended  final_grade  final_exam                 name
0         78.50         1        99.38          46         Linnie Lietz
3         69.00         1        92.50          38    Kimberely Conwell
5         63.00         1        89.38          36         Almeda Rizer
15        71.00         1        90.63          40          Mercy Dugal
16        77.00         1       101.25          46      Augustine Clair
27        75.00         1       101.25          45        Codi Whitcher
32        72.00         1        94.69          38           Nan Castro
36        73.00         1        87.81          33        Fern Iadarola
38        74.50         1        98.13          43        Delilah Starr
41        77.00         1       100.00          43         Maisie Monti
43        74.00         1        99.06          46        Shenna Tregre
44        68.00         1        89.38          35         Owen Meagher
46        70.00         1        91.25          38      Carolyne Soltis
60        74.00         1        90.94          36       Dulcie Furtado
63        75.50         1        93.13          38        Liberty Elzey
78        73.00         1        94.38          42            Min Peake
83        75.50         1       101.25          46          Tamica Wann
84        74.50         1        94.69          39       Danette Prisco
103       78.50         1       100.31          47        Nicolasa Benn
109       63.00         1        89.38          38      Kathryn Dickens
113       64.00         1        93.75          43    Annabelle Brierly
117       76.25         1        98.91          44       Dalila Sonntag
121       54.00         1       101.07          47       Laila Daddario
132       69.75         1        85.47          33      Clemente Griner
138       73.50         1        96.25          40      Claudette Ownby
142       77.00         1        97.50          40          Don Connell
148       65.50         1        86.25          38       Laurie Braziel
150       78.00         1        96.25          38  Shavonda Oesterling
151       77.00         1        93.75          40          Cristi Chae
155       78.00         1        99.38          42      Latarsha Madore
159       77.50         1       100.00          45        Carlyn Matson
162       73.50         1        95.63          39          Les Shehorn
163       72.50         1        94.38          39      Demarcus Kenney
------------ 3b ------------
     quiz_total  attended  final_grade  final_exam                 name
1         64.25         0        95.78          45        Mitch Mustain
2         76.75         0        97.42          41       Salina Chavera
4         64.00         0        92.50          39            Zack Burk
6         73.50         0        95.94          43        Damien Ellett
7         70.50         0        95.00          40        Lora Sobieski
..          ...       ...          ...         ...                  ...
166       73.50         0        96.25          45           Dana Malta
167       75.50         0        98.13          44         Sixta Heyden
168       41.00         0        69.38          32       Brianne Broome
169       77.00         0       101.25          47  Elouise Weatherholt
170       72.00         0        92.81          38        Addie Maharaj

[138 rows x 5 columns]
------------ 3c ------------
       quiz_total  attended  final_grade  final_exam
count   33.000000      33.0    33.000000   33.000000
mean    72.500000       1.0    95.072121   40.636364
std      5.547029       0.0     4.673980    4.014179
min     54.000000       1.0    85.470000   33.000000
25%     70.000000       1.0    91.250000   38.000000
50%     74.000000       1.0    94.690000   40.000000
75%     77.000000       1.0    99.380000   44.000000
max     78.500000       1.0   101.250000   47.000000
------------ 3d ------------
       quiz_total  attended  final_grade  final_exam
count  138.000000     138.0   138.000000  138.000000
mean    68.326087       0.0    91.086159   39.442029
std     10.057028       0.0    10.174000    5.800853
min      0.000000       0.0     2.500000    0.000000
25%     65.000000       0.0    88.320000   37.000000
50%     71.000000       0.0    92.770000   40.000000
75%     75.375000       0.0    96.210000   43.750000
max     79.500000       0.0   104.380000   49.000000

Describe what you find about the averages:
* The average quizzes grade for those who attended is 72.50,and for those who did not attend is 68.32.
* The average final grade for those who attended is 95.07, and for those who did not attend is 91.08.
* The average final exam score for those who attended is 40.63, and for those who did not attend is 39.44.
For all three columns, the students who attended class had higher scores than the students who did not attend class.

# Block 4

In [46]:
# was anyone working together (e.g. they had the same scores)?
duplicate_scores = data.duplicated(subset=['quiz_total', 'final_grade', 'final_exam'], keep=False)
print('------------ 4a ------------')
print (duplicate_scores)

print('------------ 4b ------------')
print(data.loc[146])
print(data.loc[170])

print('------------ 4c ------------')
print(data.loc[146]['name'])
print(data.loc[170]['name'])

------------ 4a ------------
0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
111    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
125    False
126    False
127    False
128    False
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140    False
141    False
142    False
143    False
144    False
145    False
146     True
147    False
148    False
149    False
150    False
151    False
152    False
153    False
154    False
155    False
156    False
157    False
158    False
159    False
160    False
161    False
162    False
163    False
164    False
165    False
166    False
167    False
168    False
169    False
170     True
dtype: bool
------------ 4b ------------
quiz_total                72
attended                   0
final_grade            92.81
final_exam                38
name           Jaraham Eidda
Name: 146, dtype: object
quiz_total                72
attended                   0
final_grade            92.81
final_exam                38
name           Addie Maharaj
Name: 170, dtype: object
------------ 4c ------------
Jaraham Eidda
Addie Maharaj